name: "Test Artifact Download"
on:
  workflow_dispatch:
    inputs:
      runId:
        description: "Legis Run ID With artifact"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: foo
          repository: vladroff/legis
          github-token: ${{ secrets.LEGIS_ACCESS_TOKEN }}
          run-id: '${{ inputs.runId }}'
