name: "Test Artifact Download"
on:
  workflow_dispatch:
    inputs:
      artifact-id:
        description: "Legis Artifact ID"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: foo
          repository: vladroff/legis
          github-token: ${{ secrets.LEGIS_ACCESS_TOKEN }}
          artifact-ids: '${{ inputs.artifact-id }}'
      - run: ls -R **
